name: "Deploy Now: Orchestration"

on:
  - push
  - workflow_dispatch

jobs:
  retrieve-project:
    name: check readiness
    runs-on: ubuntu-latest
    outputs:
      deployment-enabled: ${{ steps.extract.outputs.deployment-enabled }}
      branch-id: ${{ steps.extract.outputs.branch-id }}
    steps:
      - name: Fetch project data
        id: project
        uses: ionos-deploy-now/project-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-us.ionos.space
          project-id: fd29c00f-381f-4480-a921-f5edfb7b8f97
          action: retrieve-info

      - name: Extract project outputs
        id: extract
        run: |
          echo "deployment-enabled=$(echo '${{ steps.project.outputs.info }}' | jq -r '.deployment-enabled')" >> $GITHUB_OUTPUT
          echo "branch-id=$(echo '${{ steps.project.outputs.info }}' | jq -r '.branch-id')" >> $GITHUB_OUTPUT

  build:
    name: build
    needs: retrieve-project
    if: ${{ needs.retrieve-project.outputs.deployment-enabled == 'true' }}
    uses: ./.github/workflows/Web-Code-Academy-build.yaml
    with:
      site-url: https://IONOS_DEPLOY_NOW_SITE_URL
      branch-id: ${{ needs.retrieve-project.outputs.branch-id }}
    secrets: inherit

  deploy:
    name: trigger deployment
    needs:
      - retrieve-project
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch deployment(s)
        uses: ionos-deploy-now/project-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-us.ionos.space
          project-id: fd29c00f-381f-4480-a921-f5edfb7b8f97
          branch-id: ${{ needs.retrieve-project.outputs.branch-id }}
          action: dispatch-deployments
